name: Test
on: [push, pull_request]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
        id: go

      - uses: actions/checkout@v2

      - name: Test
        run: |
          go install
          go test
